workflows:
  android-workflow:
    name: Android Workflow
    environment:
      android_signing:
        - Calculator
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab